on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test -race -v ./...
    - name: Fuzz regression
      env:
        FUZZIT_API_KEY: ${{ secrets.FUZZIT_API_KEY }}
      run: ./fuzzit.sh local-regression
    - name: Fuzz
      if: github.event_name == 'push' && github.ref == 'master'
      env:
        FUZZIT_API_KEY: ${{ secrets.FUZZIT_API_KEY }}
      run: ./fuzzit.sh fuzzing